### ISSUE TITLE
Syntax errors in tools/covert_csv2jsonl.py

### ISSUE THREAD

**Issue by yujiorama** [chakki-works/Japanese-Company-Lexicon#7]
There are some syntax errors in `tools/convert_csv2jsonl.py`.

## Problem

`scripts/generate_alias.sh` can't generate collect outputs.

```
$ source scripts/generate_alias.sh
=== Company Alias Generation ===
Convert CSV to JSONL...
  File "tools/covert_csv2jsonl.py", line 61
    print("=== Read CSV files... ==="")
                                      ^
SyntaxError: EOL while scanning string literal
Generate alias...
Traceback (most recent call last):
  File "tools/alias_generation.py", line 292, in <module>
    alias = AliasGenerator.read_json(company_path)
  File "tools/alias_generation.py", line 58, in read_json
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user01/ghq/github.com/chakki-works/Japanese-Company-Lexicon/data/hojin/output/company.jsonl'
Filter alias...
JCL filtered files generation process...
Traceback (most recent call last):
  File "tools/jcl_filter.py", line 61, in <module>
    jcl_pipeline(path) # filtering names to decrease annotation error
  File "tools/jcl_filter.py", line 37, in jcl_pipeline
    with open(input_path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user01/ghq/github.com/chakki-works/Japanese-Company-Lexicon/data/hojin/output/jcl_full.csv'
=== Company Alias Generation Done ===
```

## Description

```
$ git diff -- tools/covert_csv2jsonl.py
diff --git a/tools/covert_csv2jsonl.py b/tools/covert_csv2jsonl.py
index 0c3d5bd..04dc158 100644
--- a/tools/covert_csv2jsonl.py
+++ b/tools/covert_csv2jsonl.py
@@ -58,7 +58,7 @@ class Company:
   def parse_csv(self, file_paths: List[str]) -> None:
     """Parse all csv file to get company related field
     """
-    print("=== Read CSV files... ==="")
+    print("=== Read CSV files... ===")
     for path in tqdm(file_paths):
       df = pd.read_csv(path, names=self.column_names)
       self.total_data += df.shape[0]
@@ -93,7 +93,7 @@ class Company:
     print("=== DONE! ===\n")

   def save_names(self, output_file) -> None:
-    print("=== Save companies names and frequency to CSV... ==="")
+    print("=== Save companies names and frequency to CSV... ===")
     with open(output_file, 'w', encoding='utf-8') as f:
       self.names = {k: v for k, v in sorted(self.names.items(), key=lambda item: item[1], reverse=True)}
       for name, value in tqdm(self.names.items()):
```

**Comment by BrambleXu** [comment]
Thanks for the feedback.
https://github.com/chakki-works/Japanese-Company-Lexicon/pull/6
